// Generated by CoffeeScript 1.6.3
(function() {
  var say;

  say = function(text) {
    return console.log(text);
  };

  $.ready = function() {
    return $('button.tinker').click(function() {
      var pegex_input, tinker_output, tinker_url, yaml_input;
      pegex_input = $('.pegex').val();
      yaml_input = $('.yaml').val();
      tinker_url = 'http://localhost:3000/tinker?yaml=' + escape(yaml_input);
      return tinker_output = $.get(tinker_url, function(data) {
        return $('pre.output').html(_.escape(data));
      });
    });
  };

}).call(this);
