// Generated by CoffeeScript 1.4.0
(function() {
  var say;

  say = function(text) {
    return console.log(text);
  };

  $.ready = function() {
    return $('button.tinkertest').click(function() {
      var pegex_input, tinker_url, tinkertest_output, yaml_input;
      pegex_input = $('.pegex').val();
      yaml_input = $('.yaml').val();
      tinker_url = '/tinker?yaml=' + escape(yaml_input);
      return tinkertest_output = $.get(tinker_url, function(data) {
        return $('pre.output').html(_.escape(data));
      });
    });
  };

}).call(this);
